import type { Metadata } from "next";
import { Lobster_Two, Prata  } from "next/font/google";
import "../global/global.scss";

const prata = Prata({
  subsets: ['cyrillic'],
  display: 'swap',
  weight: '400',
  variable: '--second-family'
})

const lobster = Lobster_Two({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-family'
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${lobster.variable} ${prata.variable}`}>
      <body>{children}</body>
    </html>
  );
}
